### PR TITLE
feat: markup

### PR DESCRIPTION
**Pull request by veralea**
Final project Stage 2

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hey! I'm very sorry for the delay with the review
Great job on your second diploma stage! A few fixes will be requried, but I believe you'll handle it with ease. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The dimensions and position do not differ from the layout by more than `30px` on the desktop version and by `10px` on the other screen sizes for which the layout is prepared. Differences in size should not visually contradict the layout and get out of the grid in the layout.
* No distance between cards and footer on "saved articles" page http://joxi.ru/J2bdy8DtqYY9Xr http://joxi.ru/D2PNE53cw1Rk7r
* Incorrect size of the sign button (not logged one)
* Please reset `error__search-title` default vertical margins
* Incorrect distance between `news-card-list__title` and `news-card-list__cards-grid` on 768 viewport
* Incorrect size of the `popup__close-button` on 768 viewport
* Navigation text and buttons should be centered horizontally on 320 viewport
* Navigation is displayed incorrectly on 320 viewport http://joxi.ru/vAWEMaLu3KVqRm
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the `overflow: hidden` declaration.
* The page scrolls horizontally when popup/navigation opens on 320px - 480px screen resolutions http://joxi.ru/D2PNE53cw1RvBr and on 1000+ screen width http://joxi.ru/n2YpB3ZckV5w1m
* Footer shouldn't overlap another section content on all intermediate screen resolutions http://joxi.ru/Rmzj54bHvG5jRm
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- Link to github account does not open
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 59

**Comment by veralea** [comment]
Hi! Thank you for review. I fixed errors according with your comments.

**Comment by FiLLa-FaS** [comment]
@veralea hey! I'm sorry for this delay, but you have to send your project back in practicum review interface, so I can get access to your new iteration there. Thank you!

**Comment by veralea** [comment]
Hi! I sent link in practicum review interface. Please, check it.

**Comment by FiLLa-FaS** [comment]
Hey! Thank you for your patience. Your project looks amazing! You've got 100 points, so your project is accepted. Good luck on the next diploma stage!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The dimensions and position do not differ from the layout by more than `30px` on the desktop version and by `10px` on the other screen sizes for which the layout is prepared. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the `overflow: hidden` declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 100

**Pull request merged**
